// This file was generated by robots; DO NOT EDIT.
// run: 'make generate' to regenerate this file.

package postgres

// selectUsernameUniqueCheck sql query
var selectUsernameUniqueCheck = `SELECT
	1
FROM public.users
WHERE username = $1
LIMIT 1`

// selectEmailUniqueCheck sql query
var selectEmailUniqueCheck = `SELECT
	1
FROM public.users
WHERE email = $1
LIMIT 1`

// insertUser sql query
var insertUser = `INSERT INTO public.users
(
	uid,
	username,
	email,
	password,
	created_at,
	updated_at
)
VALUES (
	$1,
	$2,
	$3,
	$4,
	$5,
	$6
)
RETURNING id`

// deleteUser sql query
var deleteUser = `DELETE FROM public.users
WHERE id = $1`

// selectUsers sql query
var selectUsers = `SELECT
	users.id,
	users.uid,
	users.username,
	users.email,
	users.created_at,
	users.updated_at
FROM public.users
ORDER BY created_at ASC`

// selectUserByID sql query
var selectUserByID = `SELECT
	users.id,
	users.uid,
	users.username,
	users.email,
	users.created_at,
	users.updated_at
FROM public.users
WHERE id = $1
LIMIT 1`

// selectUserByUID sql query
var selectUserByUID = `SELECT
	users.id,
	users.uid,
	users.username,
	users.email,
	users.created_at,
	users.updated_at
FROM public.users
WHERE uid = $1
LIMIT 1`

// selectUserByEmail sql query
var selectUserByEmail = `SELECT
	users.id,
	users.uid,
	users.username,
	users.email,
	users.created_at,
	users.updated_at
FROM public.users
WHERE email = $1
LIMIT 1`

// selectUserByEmailWithPassword sql query
var selectUserByEmailWithPassword = `SELECT
	users.id,
	users.uid,
	users.username,
	users.email,
	users.created_at,
	users.updated_at,
	user.password
FROM public.users
WHERE email = $1
LIMIT 1`

// selectUserByUsername sql query
var selectUserByUsername = `SELECT
	users.id,
	users.uid,
	users.username,
	users.email,
	users.created_at,
	users.updated_at
FROM public.users
WHERE username = $1
LIMIT 1`
