// This file was generated by robots; DO NOT EDIT.
// run: 'make generate' to regenerate this file.

package postgres

// selectUsernameUniqueCheck sql query
var selectUsernameUniqueCheck = `SELECT
	1
FROM public.user
WHERE id = $1
LIMIT 1`

// selectEmailUniqueCheck sql query
var selectEmailUniqueCheck = `SELECT
	1
FROM public.user
WHERE email = $1
LIMIT 1`

// insertUser sql query
var insertUser = `INSERT INTO public.user
(
	uid,
	username,
	email,
	password,
	created_at,
	updated_at
)
VALUES (
	$1,
	$2,
	$3,
	$4,
	$5,
	$6
)
RETURNING id`
