// This file was generated by robots; DO NOT EDIT.
// run: 'make generate' to regenerate this file.

package seed

import (
	"database/sql"
	"github.com/dwethmar/atami/pkg/database"

	"time"

	"github.com/dwethmar/atami/pkg/domain/entity"
)

// UserSQL seed query
var UserSQL = `INSERT INTO app_user
(
	uid,
	username,
	password,
	email,
	biography,
	created_at,
	updated_at
)
VALUES (
	$1,
	$2,
	$3,
	$4,
	$5,
	$6,
	$7
)`

func SeedUser(
	db database.Transaction,
	UID entity.UID,
	username string,
	password string,
	email string,
	biography string,
	createdAt time.Time,
	updateddAt time.Time,
) (sql.Result, error) {
	return db.Exec(
		UserSQL,
		UID,
		username,
		password,
		email,
		biography,
		createdAt,
		updateddAt,
	)
}

// MessageSQL seed query
var MessageSQL = `INSERT INTO message
(
	uid,
	text,
	created_by_user_id,
	created_at,
	updated_at
)
VALUES (
	$1,
	$2,
	$3,
	$4,
	$5
)`

func SeedMessage(
	db database.Transaction,
	UID string,
	text string,
	createdByUserID entity.ID,
	createdAt time.Time,
	updatedAt time.Time,
) (sql.Result, error) {
	return db.Exec(
		MessageSQL,
		UID,
		text,
		createdByUserID,
		createdAt,
		updatedAt,
	)
}
