// The following directive is necessary to make the package coherent:

// +build ignore

// This program generates contributors.go. It can be invoked by running
// go generate
package main

import (
	"fmt"
	"log"
	"os"
	"text/template"
	"time"

	qb "github.com/dwethmar/atami/pkg/database/querybuilder"
	"github.com/dwethmar/atami/pkg/user/postgres/schema"
)

// var insertUser = fmt.Sprintf(`
// INSERT INTO %s (
// 	uid,
// 	username,
// 	email,
// 	password,
// 	created_at,
// 	updated_at
// )
// VALUES ($1, $2, $3, $4, $5, $6) RETURNING id`, tableName)

var queries = []struct {
	Name  string
	Query string
}{
	{
		"selectUsernameUniqueCheck",
		qb.Select(
			qb.SelectQuery{
				From:  schema.Table,
				Cols:  []string{"1"},
				Where: qb.NewWhere().And(fmt.Sprintf("%s = $1", schema.ColID)),
				Limit: 1,
			},
		),
	},
	{
		"selectEmailUniqueCheck",
		qb.Select(
			qb.SelectQuery{
				From:  schema.Table,
				Cols:  []string{"1"},
				Where: qb.NewWhere().And(fmt.Sprintf("%s = $1", schema.ColEmail)),
				Limit: 1,
			},
		),
	},
	{
		"insertUser",
		qb.Insert(
			qb.InsertQuery{
				Into: schema.Table,
				Cols: []string{
					schema.ColUID,
					schema.ColUsername,
					schema.ColEmail,
					schema.ColPassword,
					schema.ColCreatedAt,
					schema.ColUpdatedAt,
				},
				Values: []interface{}{
					"$1", "$2", "$3", "$4", "$5", "$6",
				},
				Returning: []string{schema.ColID},
			},
		),
	},
}

func main() {
	f, err := os.Create("sql.go")
	die(err)
	defer f.Close()

	packageTemplate.Execute(f, struct {
		Timestamp time.Time
		Queries   []struct {
			Name  string
			Query string
		}
	}{
		Timestamp: time.Now(),
		Queries:   queries,
	})
}

func die(err error) {
	if err != nil {
		log.Fatal(err)
	}
}

var packageTemplate = template.Must(template.New("").Parse(`// This file was generated by robots; DO NOT EDIT.
// run: 'make generate' to regenerate this file.

package postgres
{{ range .Queries }}
// {{ .Name }} sql query
var {{ .Name }} = ` + "`" + `{{ .Query }}` + "`" + `
{{ end }}`))
