// This file was generated by robots; DO NOT EDIT.
// run: 'make generate' to regenerate this file.

package postgres

import (
	"database/sql"

	"time"
)

// selectMessages sql query
var selectMessages = `SELECT
	message.id,
	message.uid,
	message.text,
	message.created_by_user_id,
	message.created_at
FROM public.message
ORDER BY created_at DESC
LIMIT $1
OFFSET $2`

func querySelectMessages(
	db *sql.DB,
	limit int,
	offset int,
) (*sql.Rows, error) {
	return db.Query(
		selectMessages,
		limit,
		offset,
	)
}

// selectMessageByID sql query
var selectMessageByID = `SELECT
	message.id,
	message.uid,
	message.text,
	message.created_by_user_id,
	message.created_at
FROM public.message
WHERE id = $1`

func queryRowSelectMessageByID(
	db *sql.DB,
	ID int,
) *sql.Row {
	return db.QueryRow(
		selectMessageByID,
		ID,
	)
}

// deleteMessage sql query
var deleteMessage = `DELETE FROM public.message
WHERE id = $1`

func execDeleteMessage(
	db *sql.DB,
	ID int,
) (sql.Result, error) {
	return db.Exec(
		deleteMessage,
		ID,
	)
}

// insertMessage sql query
var insertMessage = `INSERT INTO public.message
(
	uid,
	text,
	created_by_user_id,
	created_at
)
VALUES (
	$1,
	$2,
	$3,
	$4
)
RETURNING id`

func queryRowInsertMessage(
	db *sql.DB,
	UID string,
	text string,
	CreatedByUserID int,
	createdAt time.Time,
) *sql.Row {
	return db.QueryRow(
		insertMessage,
		UID,
		text,
		CreatedByUserID,
		createdAt,
	)
}
