// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots at
// 2020-11-17 22:44:48.763118164 +0100 CET m=+0.000602692
package postgres

// getMessages sql query
var getMessages = `SELECT 
	message.id, 
	message.uid, 
	message.text, 
	message.created_by_user_id, 
	message.created_at
FROM public.message
ORDER BY message.created_at DESC
LIMIT $1
OFFSET $2`

// getMessageByID sql query
var getMessageByID = `SELECT 
	message.id, 
	message.uid, 
	message.text, 
	message.created_by_user_id, 
	message.created_at
FROM public.message
WHERE id = $1
ORDER BY 
LIMIT $1
OFFSET $2`
