// This file was generated by robots; DO NOT EDIT.
// run: 'make generate' to regenerate this file.

package postgres

// selectMessages sql query
var selectMessages = `SELECT
	message.id,
	message.uid,
	message.text,
	message.created_by_user_id,
	message.created_at
FROM public.message
ORDER BY message.created_at DESC
LIMIT $1
OFFSET $2`

// selectMessageByID sql query
var selectMessageByID = `SELECT
	message.id,
	message.uid,
	message.text,
	message.created_by_user_id,
	message.created_at
FROM public.message
WHERE id = $1`

// insertMessage sql query
var insertMessage = `INSERT INTO public.message
(
	message.uid,
	message.text,
	message.created_by_user_id,
	message.created_at
)
VALUES (
	'$1',
	'$2',
	'$3',
	'$4'
)`

// deleteMessage sql query
var deleteMessage = `DELETE FROM public.message
WHERE id = $1`
